name: Other Request
description: Official template to report any other type of issue/request.
title: "[Other-req]: "
labels: ["type: other", "scope: awaiting triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe what needs to be done/what is failing.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
